#!/usr/bin/env node
// Generates public/sitemap.xml from the same src/seo/pages.json list that
// <PageSeo> uses for per-route titles/descriptions — one source of truth
// instead of a hand-maintained XML file that silently drifts from
// src/App.tsx's actual routes. Runs before every build (see package.json's
// "build" script) so the shipped sitemap can never go stale on its own.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import seoConfig from "../src/seo/pages.json" with { type: "json" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(__dirname, "..", "public", "sitemap.xml");

const urls = seoConfig.pages
  .map(
    (p) => `  <url>
    <loc>${seoConfig.siteUrl}${p.path}</loc>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs from src/seo/pages.json —
     do not hand-edit; add/remove a page there instead, it re-runs on every
     build. Public, indexable pages only — signed-in areas are excluded
     here and in robots.txt. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

writeFileSync(outFile, xml);
console.log(`Wrote ${outFile} (${seoConfig.pages.length} URLs)`);
